# Generated by Django 5.2.6 on 2026-09-27 04:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=140, unique=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="JobOpening",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                (
                    "summary",
                    models.TextField(
                        help_text="Shown on the careers listing.", max_length=400
                    ),
                ),
                ("description", models.TextField(help_text="What the role involves.")),
                (
                    "responsibilities",
                    models.TextField(
                        blank=True, help_text="One responsibility per line."
                    ),
                ),
                (
                    "requirements",
                    models.TextField(blank=True, help_text="One requirement per line."),
                ),
                (
                    "nice_to_have",
                    models.TextField(blank=True, help_text="One item per line."),
                ),
                (
                    "benefits",
                    models.TextField(blank=True, help_text="One benefit per line."),
                ),
                ("location", models.CharField(blank=True, max_length=160)),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("onsite", "On site"),
                            ("hybrid", "Hybrid"),
                            ("remote", "Remote"),
                        ],
                        default="onsite",
                        max_length=20,
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full time"),
                            ("part_time", "Part time"),
                            ("contract", "Contract"),
                            ("internship", "Internship"),
                        ],
                        default="full_time",
                        max_length=20,
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("entry", "Entry level"),
                            ("mid", "Mid level"),
                            ("senior", "Senior"),
                            ("lead", "Lead"),
                        ],
                        default="mid",
                        max_length=20,
                    ),
                ),
                (
                    "salary_range",
                    models.CharField(
                        blank=True,
                        help_text="Optional. Leave blank to show nothing.",
                        max_length=140,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("open", "Open"),
                            ("closed", "Closed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("posted_at", models.DateField(blank=True, null=True)),
                ("closes_at", models.DateField(blank=True, null=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("meta_title", models.CharField(blank=True, max_length=70)),
                ("meta_description", models.CharField(blank=True, max_length=180)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="openings",
                        to="careers.department",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "-posted_at", "title"],
            },
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=140)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("location", models.CharField(blank=True, max_length=160)),
                ("portfolio_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("cover_letter", models.TextField(blank=True)),
                (
                    "cv",
                    models.FileField(
                        help_text="PDF or Word document.",
                        upload_to="careers/applications/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["pdf", "doc", "docx", "odt", "rtf"]
                            )
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("reviewing", "Reviewing"),
                            ("shortlisted", "Shortlisted"),
                            ("rejected", "Not proceeding"),
                            ("hired", "Hired"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Internal notes. Never shown publicly."
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="careers.jobopening",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="jobopening",
            index=models.Index(
                fields=["is_published", "status"], name="careers_job_is_publ_2633e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobopening",
            index=models.Index(fields=["slug"], name="careers_job_slug_9ca3de_idx"),
        ),
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(
                fields=["status", "-created_at"], name="careers_job_status_13e14c_idx"
            ),
        ),
    ]
