# Generated by Django 5.2.6 on 2026-09-27 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProjectCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=130, unique=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Project categories",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=70, unique=True)),
            ],
            options={
                "verbose_name_plural": "Technologies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=140)),
                ("slug", models.SlugField(max_length=160, unique=True)),
                (
                    "short_description",
                    models.CharField(
                        help_text="One or two lines shown on project cards.",
                        max_length=300,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Overview section of the case study."
                    ),
                ),
                (
                    "problem",
                    models.TextField(
                        blank=True, help_text="The problem the software addresses."
                    ),
                ),
                (
                    "solution",
                    models.TextField(blank=True, help_text="What was actually built."),
                ),
                (
                    "result",
                    models.TextField(
                        blank=True,
                        help_text="What was delivered. Do not add user counts or metrics unless they are verified.",
                    ),
                ),
                (
                    "architecture_description",
                    models.TextField(
                        blank=True,
                        help_text="Plain-text description of the deployed architecture. Leave blank to hide the section.",
                    ),
                ),
                (
                    "architecture_diagram",
                    models.ImageField(blank=True, upload_to="projects/architecture/"),
                ),
                (
                    "client",
                    models.CharField(
                        blank=True,
                        help_text="Only fill this in for real, named clients who agreed to be listed.",
                        max_length=160,
                    ),
                ),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "Planning"),
                            ("development", "Development"),
                            ("live", "Live"),
                            ("maintenance", "Maintenance"),
                            ("archived", "Archived"),
                        ],
                        default="development",
                        max_length=20,
                    ),
                ),
                ("website_url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                (
                    "cover_image",
                    models.ImageField(blank=True, upload_to="projects/covers/"),
                ),
                ("cover_image_alt", models.CharField(blank=True, max_length=180)),
                (
                    "featured",
                    models.BooleanField(
                        default=False,
                        help_text="Featured projects appear on the homepage.",
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("meta_title", models.CharField(blank=True, max_length=70)),
                ("meta_description", models.CharField(blank=True, max_length=180)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projects",
                        to="projects.projectcategory",
                    ),
                ),
                (
                    "technologies",
                    models.ManyToManyField(
                        blank=True, related_name="projects", to="projects.technology"
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "-year", "title"],
            },
        ),
        migrations.CreateModel(
            name="ProjectChallenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=140)),
                ("description", models.TextField(blank=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="challenges",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProjectFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=140)),
                ("description", models.TextField(blank=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="projects/gallery/")),
                ("alt_text", models.CharField(max_length=180)),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["is_published", "featured", "display_order"],
                name="projects_pr_is_publ_a18c5a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["slug"], name="projects_pr_slug_042165_idx"),
        ),
    ]
