# Generated by Django 5.2.6 on 2026-09-27 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name of the site owner.", max_length=120
                    ),
                ),
                (
                    "brand_name",
                    models.CharField(
                        help_text="Brand shown in the navigation bar, e.g. TECHMIARY.",
                        max_length=80,
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True,
                        help_text="Registered company or trading name, e.g. Techmiary Technology Concepts.",
                        max_length=160,
                    ),
                ),
                (
                    "professional_title",
                    models.CharField(
                        help_text="Primary positioning line, e.g. Software Engineer & Product Builder.",
                        max_length=160,
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True,
                        help_text="Secondary positioning line shown under the title.",
                        max_length=255,
                    ),
                ),
                (
                    "short_bio",
                    models.TextField(
                        help_text="One or two sentences used in the hero and meta description."
                    ),
                ),
                (
                    "long_bio",
                    models.TextField(
                        blank=True, help_text="Full biography for the About page."
                    ),
                ),
                ("profile_image", models.ImageField(blank=True, upload_to="site/")),
                (
                    "og_image",
                    models.ImageField(
                        blank=True,
                        help_text="1200x630 image used for link previews.",
                        upload_to="site/",
                    ),
                ),
                ("logo", models.ImageField(blank=True, upload_to="site/")),
                ("favicon", models.ImageField(blank=True, upload_to="site/")),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("location", models.CharField(blank=True, max_length=160)),
                (
                    "show_email_publicly",
                    models.BooleanField(
                        default=False,
                        help_text="Leave off to keep the address out of the page source; the contact form still reaches it.",
                    ),
                ),
                ("github_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("whatsapp_url", models.URLField(blank=True)),
                (
                    "website_url",
                    models.URLField(blank=True, help_text="Primary company website."),
                ),
                ("resume_file", models.FileField(blank=True, upload_to="resume/")),
                (
                    "legal_name",
                    models.CharField(
                        blank=True,
                        help_text="Registered name, if different from the trading name.",
                        max_length=200,
                    ),
                ),
                (
                    "founded_year",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Year the company started operating.",
                        null=True,
                    ),
                ),
                (
                    "hero_headline",
                    models.CharField(
                        blank=True,
                        help_text="Main homepage headline. Falls back to the positioning line.",
                        max_length=160,
                    ),
                ),
                (
                    "hero_subheadline",
                    models.TextField(
                        blank=True, help_text="Paragraph under the homepage headline."
                    ),
                ),
                (
                    "company_overview",
                    models.TextField(
                        blank=True,
                        help_text="What the company does. Used on the About page.",
                    ),
                ),
                ("mission", models.TextField(blank=True)),
                ("vision", models.TextField(blank=True)),
                (
                    "address",
                    models.TextField(blank=True, help_text="Full postal address."),
                ),
                (
                    "office_hours",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Monday to Friday, 9am – 5pm WAT.",
                        max_length=160,
                    ),
                ),
                ("support_email", models.EmailField(blank=True, max_length=254)),
                ("sales_email", models.EmailField(blank=True, max_length=254)),
                ("secondary_phone", models.CharField(blank=True, max_length=40)),
                (
                    "registration_number",
                    models.CharField(
                        blank=True,
                        help_text="Company registration number, if you display one.",
                        max_length=80,
                    ),
                ),
                (
                    "newsletter_blurb",
                    models.CharField(
                        blank=True,
                        help_text="One line above the newsletter form. Falls back to a default.",
                        max_length=255,
                    ),
                ),
                ("meta_title", models.CharField(blank=True, max_length=70)),
                ("meta_description", models.CharField(blank=True, max_length=180)),
                (
                    "twitter_handle",
                    models.CharField(
                        blank=True,
                        help_text="Without the @, e.g. techmiary.",
                        max_length=40,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site settings",
                "verbose_name_plural": "Site settings",
            },
        ),
        migrations.CreateModel(
            name="SkillCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=90, unique=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Skill categories",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("url", models.URLField()),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("github", "GitHub"),
                            ("linkedin", "LinkedIn"),
                            ("x", "X"),
                            ("facebook", "Facebook"),
                            ("whatsapp", "WhatsApp"),
                            ("instagram", "Instagram"),
                            ("youtube", "YouTube"),
                            ("link", "Generic link"),
                        ],
                        default="link",
                        max_length=20,
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                (
                    "kind",
                    models.CharField(
                        choices=[("partner", "Partner"), ("trusted", "Trusted by")],
                        default="partner",
                        help_text="Partners are collaborators; Trusted by are organisations you have delivered for.",
                        max_length=20,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Upload a dark version — the site background is light blue. Leave empty to show the name as a wordmark instead.",
                        upload_to="partners/",
                    ),
                ),
                (
                    "logo_alt",
                    models.CharField(
                        blank=True,
                        help_text="Defaults to the organisation name.",
                        max_length=180,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True, help_text="Optional link to their website."
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        blank=True,
                        help_text="One short line, e.g. Infrastructure partner. Shown under the name.",
                        max_length=200,
                    ),
                ),
                (
                    "consent_on_file",
                    models.BooleanField(
                        default=False,
                        help_text="Tick once the organisation has agreed to be named here.",
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_order", "name"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "kind", "display_order"],
                        name="core_partne_is_acti_d422d5_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kind", "name"), name="unique_partner_per_kind"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "proficiency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Not stated"),
                            ("working", "Working knowledge"),
                            ("proficient", "Proficient"),
                            ("primary", "Primary tool"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="core.skillcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "name"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "display_order"],
                        name="core_skill_is_acti_e7062e_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("category", "name"), name="unique_skill_per_category"
                    )
                ],
            },
        ),
    ]
