# Generated by Django 5.2.6 on 2026-10-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="bank_account_name",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="bank_account_number",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="bank_name",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
