# Generated by Django 5.2.6 on 2026-09-27 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0001_initial"),
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(blank=True, max_length=140)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("footer", "Footer form"),
                            ("insights", "Insights page"),
                            ("resources", "Resources page"),
                            ("admin", "Added by an administrator"),
                        ],
                        default="footer",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Untick instead of deleting when someone unsubscribes.",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("unsubscribed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40)),
                (
                    "company",
                    models.CharField(
                        blank=True,
                        max_length=160,
                        verbose_name="Company / organisation",
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("read", "Read"),
                            ("replied", "Replied"),
                            ("spam", "Spam"),
                        ],
                        default="new",
                        max_length=10,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="contact_con_status_4b75ca_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="QuoteRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "budget_range",
                    models.CharField(
                        choices=[
                            ("undecided", "Not decided yet"),
                            ("under_1m", "Under ₦1,000,000"),
                            ("1m_5m", "₦1,000,000 – ₦5,000,000"),
                            ("5m_15m", "₦5,000,000 – ₦15,000,000"),
                            ("over_15m", "Above ₦15,000,000"),
                        ],
                        default="undecided",
                        max_length=20,
                    ),
                ),
                (
                    "timeline",
                    models.CharField(
                        choices=[
                            ("asap", "As soon as possible"),
                            ("1_3_months", "Within 1–3 months"),
                            ("3_6_months", "Within 3–6 months"),
                            ("exploring", "Still exploring"),
                        ],
                        default="exploring",
                        max_length=20,
                    ),
                ),
                (
                    "existing_system",
                    models.BooleanField(
                        default=False,
                        help_text="Whether they already run a system this must replace.",
                    ),
                ),
                ("contact_name", models.CharField(max_length=140)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("organisation", models.CharField(blank=True, max_length=180)),
                (
                    "organisation_type",
                    models.CharField(
                        choices=[
                            ("school", "School or college"),
                            ("business", "Business"),
                            ("government", "Government or agency"),
                            ("ngo", "NGO or non-profit"),
                            ("startup", "Startup"),
                            ("individual", "Individual"),
                            ("other", "Other"),
                        ],
                        default="business",
                        max_length=20,
                    ),
                ),
                ("country", models.CharField(blank=True, max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("reviewing", "Reviewing"),
                            ("quoted", "Quote sent"),
                            ("won", "Won"),
                            ("closed", "Closed"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("internal_notes", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quote_requests",
                        to="services.service",
                    ),
                ),
                (
                    "solution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quote_requests",
                        to="company.solution",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quote request",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="contact_quo_status_7dc4a9_idx",
                    )
                ],
            },
        ),
    ]
