# Generated by Django 5.2.6 on 2026-09-27 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=140)),
                ("slug", models.SlugField(blank=True, max_length=160, unique=True)),
                ("summary", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        default="code",
                        help_text="Icon key rendered by the template, e.g. code, cloud, school, api.",
                        max_length=40,
                    ),
                ),
                (
                    "deliverables",
                    models.TextField(blank=True, help_text="One deliverable per line."),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Featured services appear on the homepage.",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "title"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "display_order"],
                        name="services_se_is_acti_f7c341_idx",
                    )
                ],
            },
        ),
    ]
