# Generated by Django 5.2.6 on 2026-09-27 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=90, unique=True)),
                ("description", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name": "Blog category",
                "verbose_name_plural": "Blog categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                (
                    "excerpt",
                    models.TextField(
                        help_text="Shown on cards and used as the meta description.",
                        max_length=400,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Body text. Blank lines separate paragraphs."
                    ),
                ),
                ("featured_image", models.ImageField(blank=True, upload_to="blog/")),
                ("featured_image_alt", models.CharField(blank=True, max_length=180)),
                ("published", models.BooleanField(default=False)),
                ("is_featured", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("meta_title", models.CharField(blank=True, max_length=70)),
                ("meta_description", models.CharField(blank=True, max_length=180)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blog_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to="blog.blogcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["published", "-published_at"],
                        name="blog_blogpo_publish_171661_idx",
                    ),
                    models.Index(fields=["slug"], name="blog_blogpo_slug_361555_idx"),
                ],
            },
        ),
    ]
