# Generated by Django 5.2.6 on 2026-09-27 05:56

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Proposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Generated on first save, e.g. TMY-2026-0007.",
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("client_organisation", models.CharField(max_length=200)),
                ("client_contact_name", models.CharField(max_length=160)),
                (
                    "client_role",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Proprietor, Head Teacher, IT Manager.",
                        max_length=120,
                    ),
                ),
                ("client_email", models.EmailField(blank=True, max_length=254)),
                ("client_phone", models.CharField(blank=True, max_length=40)),
                ("client_address", models.TextField(blank=True)),
                (
                    "title",
                    models.CharField(
                        help_text="e.g. School Management System.", max_length=200
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        help_text="One line, shown under the title.", max_length=300
                    ),
                ),
                (
                    "background",
                    models.TextField(
                        blank=True, help_text="The client's current situation."
                    ),
                ),
                (
                    "approach",
                    models.TextField(blank=True, help_text="How the work will be run."),
                ),
                (
                    "assumptions",
                    models.TextField(blank=True, help_text="One per line."),
                ),
                (
                    "exclusions",
                    models.TextField(
                        blank=True, help_text="One per line. What is not included."
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("NGN", "Naira (₦)"),
                            ("USD", "US Dollar ($)"),
                            ("GBP", "Pound (£)"),
                            ("EUR", "Euro (€)"),
                        ],
                        default="NGN",
                        max_length=3,
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "tax_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="VAT or equivalent. Leave at 0 if not applicable.",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "deposit_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("50"),
                        help_text="Percentage payable to begin work.",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                ("payment_terms", models.TextField(blank=True)),
                (
                    "timeline_weeks",
                    models.PositiveIntegerField(
                        default=8, help_text="Estimated delivery time from kick-off."
                    ),
                ),
                (
                    "start_estimate",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Within two weeks of acceptance.",
                        max_length=120,
                    ),
                ),
                (
                    "valid_until",
                    models.DateField(
                        blank=True,
                        help_text="Blank means the proposal does not expire.",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Internal only. Never appears in the PDF."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("expired", "Expired"),
                        ],
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "prepared_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProposalItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1"), max_digits=8
                    ),
                ),
                ("unit", models.CharField(blank=True, max_length=40)),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="proposals.proposal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Line item",
                "verbose_name_plural": "Line items",
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProposalMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                ("week_from", models.PositiveIntegerField(default=1)),
                ("week_to", models.PositiveIntegerField(default=1)),
                (
                    "percent_of_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Leave at 0 if this phase is not a payment point.",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="proposals.proposal",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "week_from", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProposalTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=140, unique=True)),
                ("slug", models.SlugField(max_length=160, unique=True)),
                (
                    "summary",
                    models.CharField(
                        help_text="One line describing what this engagement delivers.",
                        max_length=300,
                    ),
                ),
                (
                    "background",
                    models.TextField(
                        blank=True,
                        help_text="The situation this kind of client is usually in. Edited per proposal.",
                    ),
                ),
                (
                    "approach",
                    models.TextField(
                        blank=True,
                        help_text="How the work is run. One paragraph per phase.",
                    ),
                ),
                (
                    "assumptions",
                    models.TextField(blank=True, help_text="One per line."),
                ),
                ("exclusions", models.TextField(blank=True, help_text="One per line.")),
                ("payment_terms", models.TextField(blank=True)),
                ("default_timeline_weeks", models.PositiveIntegerField(default=8)),
                (
                    "default_validity_days",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="How long a proposal from this template stays open.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "solution",
                    models.ForeignKey(
                        blank=True,
                        help_text="Links the proposal to a solution on the website, if it matches one.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proposal_templates",
                        to="company.solution",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proposal template",
                "verbose_name_plural": "Proposal templates",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="proposal",
            name="template",
            field=models.ForeignKey(
                blank=True,
                help_text="Pick one to prefill the scope and line items, then edit freely.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proposals",
                to="proposals.proposaltemplate",
            ),
        ),
        migrations.CreateModel(
            name="TemplateItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1"), max_digits=8
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text="e.g. module, day, licence.",
                        max_length=40,
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="proposals.proposaltemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Template line item",
                "verbose_name_plural": "Template line items",
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="proposal",
            index=models.Index(
                fields=["status", "-created_at"], name="proposals_p_status_20826d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="proposal",
            index=models.Index(
                fields=["reference"], name="proposals_p_referen_171894_idx"
            ),
        ),
    ]
