# Generated by Django 5.2.6 on 2026-10-05 18:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
        ("proposals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceListItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160, unique=True)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Shown under the line on the quotation."
                    ),
                ),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("module", "System modules"),
                            ("service", "Delivery & add-ons"),
                            ("recurring", "Licence, hosting & support"),
                        ],
                        default="module",
                        max_length=12,
                    ),
                ),
                (
                    "billing",
                    models.CharField(
                        choices=[
                            ("one_off", "One-off"),
                            ("per_student_term", "Per student, per term"),
                            ("per_term", "Per term"),
                            ("per_year", "Per year"),
                        ],
                        default="one_off",
                        max_length=20,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text="e.g. module, day, installation. Not needed for per-student lines.",
                        max_length=40,
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "default_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1"),
                        help_text="Ignored for per-student lines, which use the school's student count.",
                        max_digits=8,
                    ),
                ),
                (
                    "selected_by_default",
                    models.BooleanField(
                        default=False,
                        help_text="Pre-ticked when a new quotation is started.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Price list item",
                "verbose_name_plural": "Price list",
                "ordering": ["group", "display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SchoolQuotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Generated on first save, e.g. TMY-Q-2026-0003.",
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("school_name", models.CharField(max_length=200)),
                ("contact_name", models.CharField(max_length=160)),
                (
                    "contact_role",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Proprietor, Principal, Bursar.",
                        max_length=120,
                    ),
                ),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=40)),
                ("school_address", models.TextField(blank=True)),
                (
                    "school_type",
                    models.CharField(
                        choices=[
                            ("nursery_primary", "Nursery & primary"),
                            ("secondary", "Secondary"),
                            ("combined", "Nursery, primary & secondary"),
                            ("tertiary", "College / training institute"),
                        ],
                        default="combined",
                        max_length=20,
                    ),
                ),
                (
                    "student_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Used to price every per-student line."
                    ),
                ),
                ("campus_count", models.PositiveIntegerField(default=1)),
                (
                    "deployment",
                    models.CharField(
                        choices=[
                            ("online", "Online — hosted and maintained by us"),
                            (
                                "offline",
                                "Offline — installed on the school's computers",
                            ),
                            ("hybrid", "Online and offline"),
                        ],
                        default="online",
                        max_length=10,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("NGN", "Naira (₦)"),
                            ("USD", "US Dollar ($)"),
                            ("GBP", "Pound (£)"),
                            ("EUR", "Euro (€)"),
                        ],
                        default="NGN",
                        max_length=3,
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Applied to the one-off setup cost only.",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "tax_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="VAT, applied to every amount. Nigerian VAT is 7.5%; leave 0 if not charged.",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "deposit_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("60"),
                        help_text="Share of the one-off cost payable to begin work.",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "delivery_weeks",
                    models.PositiveIntegerField(
                        default=6, help_text="From payment of the deposit."
                    ),
                ),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("payment_terms", models.TextField(blank=True)),
                (
                    "client_notes",
                    models.TextField(
                        blank=True,
                        help_text="Printed on the quotation, under the prices.",
                    ),
                ),
                (
                    "internal_notes",
                    models.TextField(
                        blank=True, help_text="Internal only. Never printed."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "prepared_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="school_quotations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_request",
                    models.ForeignKey(
                        blank=True,
                        help_text="The website quote request this was raised from, if any.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="school_quotations",
                        to="contact.quoterequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "School quotation",
                "verbose_name_plural": "School quotations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SchoolQuotationLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True)),
                (
                    "billing",
                    models.CharField(
                        choices=[
                            ("one_off", "One-off"),
                            ("per_student_term", "Per student, per term"),
                            ("per_term", "Per term"),
                            ("per_year", "Per year"),
                        ],
                        default="one_off",
                        max_length=20,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1"),
                        help_text="Ignored for per-student lines.",
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("unit", models.CharField(blank=True, max_length=40)),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "price_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quotation_lines",
                        to="proposals.pricelistitem",
                    ),
                ),
                (
                    "quotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="proposals.schoolquotation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quotation line",
                "verbose_name_plural": "Quotation lines",
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="schoolquotation",
            index=models.Index(
                fields=["status", "-created_at"], name="proposals_s_status_81e5c8_idx"
            ),
        ),
    ]
