# Generated by Django 5.2.6 on 2026-09-27 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=140)),
                ("description", models.TextField()),
                ("icon", models.CharField(default="shield", max_length=40)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["display_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="FAQCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=140, unique=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "FAQ category",
                "verbose_name_plural": "FAQ categories",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Industry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=140, unique=True)),
                ("tagline", models.CharField(blank=True, max_length=200)),
                (
                    "summary",
                    models.TextField(help_text="What this sector needs from software."),
                ),
                ("overview", models.TextField(blank=True)),
                (
                    "challenges",
                    models.TextField(
                        blank=True,
                        help_text="One challenge per line. Rendered as a list.",
                    ),
                ),
                ("icon", models.CharField(default="school", max_length=40)),
                ("image", models.ImageField(blank=True, upload_to="industries/")),
                ("image_alt", models.CharField(blank=True, max_length=180)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Industries",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Milestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["year", "display_order"],
            },
        ),
        migrations.CreateModel(
            name="ResourceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=140, unique=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Resource categories",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255)),
                ("answer", models.TextField()),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="faqs",
                        to="company.faqcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=180)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Leave empty to show the name as a wordmark.",
                        upload_to="clients/",
                    ),
                ),
                ("logo_alt", models.CharField(blank=True, max_length=180)),
                ("website_url", models.URLField(blank=True)),
                (
                    "engagement",
                    models.CharField(
                        blank=True,
                        help_text="One line, e.g. School ERP deployment.",
                        max_length=200,
                    ),
                ),
                (
                    "consent_on_file",
                    models.BooleanField(
                        default=False,
                        help_text="Tick once the client has agreed to be named publicly.",
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "industry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clients",
                        to="company.industry",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("summary", models.TextField(max_length=400)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("guide", "Guide"),
                            ("whitepaper", "Whitepaper"),
                            ("checklist", "Checklist"),
                            ("brochure", "Brochure"),
                            ("template", "Template"),
                            ("report", "Report"),
                        ],
                        default="guide",
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(blank=True, upload_to="resources/")),
                (
                    "external_url",
                    models.URLField(
                        blank=True,
                        help_text="Use instead of a file when the resource is hosted elsewhere.",
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(blank=True, upload_to="resources/covers/"),
                ),
                ("pages", models.PositiveIntegerField(blank=True, null=True)),
                ("published_at", models.DateField(blank=True, null=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resources",
                        to="company.resourcecategory",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "-published_at", "title"],
            },
        ),
        migrations.CreateModel(
            name="Solution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=140)),
                ("slug", models.SlugField(blank=True, max_length=160, unique=True)),
                (
                    "tagline",
                    models.CharField(
                        help_text="One line shown under the name on cards.",
                        max_length=200,
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        help_text="Two or three sentences for listing pages."
                    ),
                ),
                (
                    "overview",
                    models.TextField(
                        blank=True, help_text="Full description on the detail page."
                    ),
                ),
                (
                    "who_its_for",
                    models.TextField(
                        blank=True,
                        help_text="The kind of organisation this is built for.",
                    ),
                ),
                (
                    "outcome",
                    models.TextField(
                        blank=True,
                        help_text="What an organisation can do after adopting it. State capabilities, not statistics.",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="layers",
                        help_text="Icon key rendered by the template, e.g. cloud, school, api, shield.",
                        max_length=40,
                    ),
                ),
                ("hero_image", models.ImageField(blank=True, upload_to="solutions/")),
                ("hero_image_alt", models.CharField(blank=True, max_length=180)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Featured solutions appear on the homepage.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("meta_title", models.CharField(blank=True, max_length=70)),
                ("meta_description", models.CharField(blank=True, max_length=180)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "industries",
                    models.ManyToManyField(
                        blank=True, related_name="solutions", to="company.industry"
                    ),
                ),
                (
                    "related_project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link the case study for the system this solution is based on.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solutions",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SolutionCapability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=140)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(default="check", max_length=40)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "solution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capabilities",
                        to="company.solution",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Solution capabilities",
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=140)),
                ("slug", models.SlugField(blank=True, max_length=160, unique=True)),
                ("role", models.CharField(max_length=160)),
                ("department", models.CharField(blank=True, max_length=120)),
                ("short_bio", models.CharField(blank=True, max_length=300)),
                ("bio", models.TextField(blank=True)),
                ("photo", models.ImageField(blank=True, upload_to="team/")),
                ("photo_alt", models.CharField(blank=True, max_length=180)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("linkedin_url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                (
                    "is_leadership",
                    models.BooleanField(
                        default=False,
                        help_text="Leadership members appear on the About page.",
                    ),
                ),
                (
                    "is_founder",
                    models.BooleanField(
                        default=False,
                        help_text="The founder's page also shows the career history from the Experience section.",
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["display_order", "name"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "display_order"],
                        name="company_tea_is_acti_9c7700_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quote", models.TextField()),
                ("author_name", models.CharField(max_length=140)),
                ("author_role", models.CharField(blank=True, max_length=160)),
                ("organisation", models.CharField(blank=True, max_length=180)),
                (
                    "author_photo",
                    models.ImageField(blank=True, upload_to="testimonials/"),
                ),
                (
                    "consent_on_file",
                    models.BooleanField(
                        default=False,
                        help_text="Tick once the person has approved this quote.",
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="testimonials",
                        to="company.client",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="solution",
            index=models.Index(
                fields=["is_active", "display_order"],
                name="company_sol_is_acti_2f1803_idx",
            ),
        ),
    ]
