# Generated by Django 5.2.6 on 2026-09-27 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organization", models.CharField(max_length=160)),
                ("organization_url", models.URLField(blank=True)),
                ("position", models.CharField(max_length=160)),
                ("location", models.CharField(blank=True, max_length=160)),
                ("start_date", models.DateField()),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Leave empty for a current role.",
                        null=True,
                    ),
                ),
                ("is_current", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
                (
                    "technologies",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated list, e.g. Python, Django, PostgreSQL.",
                        max_length=255,
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Experience",
                "ordering": ["display_order", "-start_date"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "display_order"],
                        name="experience__is_acti_f3460d_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Responsibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=300)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "experience",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responsibilities",
                        to="experience.experience",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Responsibilities",
                "ordering": ["display_order", "id"],
            },
        ),
    ]
